services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - apps/server/.env
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-nx_example}  # Match this with your TypeORM config
    ports:
      - '5433:5432'  # Note: You're using port 5433 locally
    volumes:
      - nx_example:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nx_example: